export type productData = {
  id: Number,
  name: string,
  image: string,
  price: number,
  shopName: string,
  distance: number,
  description: string,
  keywords: string[];
  isFeatured: boolean,
}

export const products: productData[] = [
    {
      id: 0,
      name: 'AP Royale Oak Gold',
      image: '/RoyaleOak.png',
      price: 1239,
      shopName: 'Watches & jewerlery',
      distance: 0.4,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: true,
    },
    {
      id: 1,
      name: 'Apple iPhone 12',
      image: '',
      price: 999,
      shopName: 'TechZone',
      distance: 2.5,
      description: 'Experience the next generation of iPhone with the powerful A14 Bionic chip, advanced dual-camera system, and Super Retina XDR display.',
      keywords: ['smartphone', 'iPhone', 'camera', 'iOS'],
      isFeatured: true
    },
    {
      id: 2,
      name: 'Samsung Galaxy S21',
      image: '',
      price: 899,
      shopName: 'ElectroTech',
      distance: 3.8,
      description: 'Discover the ultimate smartphone experience with the Samsung Galaxy S21. It features a stunning display, high-performance processor, and pro-grade camera system.',
      keywords: ['Android', 'Samsung', 'smartphone', 'camera'],
      isFeatured: true
    },
    {
      id: 3,
      name: 'Sony PlayStation 5',
      image: '',
      price: 499,
      shopName: 'GameWorld',
      distance: 5.2,
      description: 'Immerse yourself in extraordinary gaming experiences with the PlayStation 5. Enjoy stunning 4K graphics, lightning-fast load times, and the new DualSense controller.',
      keywords: ['gaming', 'console', 'PlayStation'],
      isFeatured: true
    },
    {
      id: 4,
      name: 'LG 55-Inch 4K Smart TV',
      image: '',
      price: 799,
      shopName: 'ElecBazaar',
      distance: 1.7,
      description: 'Bring the cinema experience home with the LG 55-inch 4K Smart TV. Enjoy vibrant colors, immersive sound, and access to a wide range of streaming services.',
      keywords: ['TV', '4K', 'smart', 'television'],
      isFeatured: true
    },
    {
      id: 5,
      name: 'Dell XPS 13 Laptop',
      image: '',
      price: 1299,
      shopName: 'PCWorld',
      distance: 4.1,
      description: 'Get the ultimate combination of performance and portability with the Dell XPS 13 Laptop. It features a stunning InfinityEdge display, powerful processors, and all-day battery life.',
      keywords: ['laptop', 'Dell', 'ultrabook', 'portable'],
      isFeatured: true
    },
    {
      id: 6,
      name: 'Canon EOS Rebel T7i DSLR Camera',
      image: '',
      price: 799,
      shopName: 'CameraLand',
      distance: 3.5,
      description: 'Capture stunning photos and videos with the Canon EOS Rebel T7i DSLR Camera. It offers high-resolution images, fast autofocus, and built-in Wi-Fi for easy sharing.',
      keywords: ['camera', 'DSLR', 'photography', 'Canon'],
      isFeatured: true
    },
    {
      id: 7,
      name: 'Bose QuietComfort 35 II Wireless Headphones',
      image: '',
      price: 349,
      shopName: 'SoundHub',
      distance: 2.9,
      description: 'Immerse yourself in your favorite music with the Bose QuietComfort 35 II Wireless Headphones. Enjoy noise-canceling technology, balanced sound, and a comfortable fit.',
      keywords: ['headphones', 'wireless', 'Bose', 'noise-canceling'],
      isFeatured: true
    },
    {
      id: 8,
      name: 'Fitbit Versa 3 Smartwatch',
      image: '',
      price: 229,
      shopName: 'FitnessGuru',
      distance: 6.3,
      description: 'Stay active and track your fitness goals with the Fitbit Versa 3 Smartwatch. It offers built-in GPS, heart rate monitoring, and access to a variety of apps and workouts.',
      keywords: ['smartwatch', 'fitness', 'health', 'activity tracker'],
      isFeatured: true
    },
    {
      id: 9,
      name: 'Nintendo Switch Console',
      image: '',
      price: 299,
      shopName: 'GameZone',
      distance: 4.8,
      description: 'Experience the joy of gaming anytime, anywhere with the Nintendo Switch Console. Play on the TV or take it on the go in handheld mode for versatile gaming options.',
      keywords: ['gaming', 'console', 'Nintendo', 'portable'],
      isFeatured: true
    },
    {
      id: 10,
      name: 'Apple MacBook Pro',
      image: '',
      price: 1999,
      shopName: 'AppleStore',
      distance: 2.1,
      description: 'Power through your tasks with the Apple MacBook Pro. It offers a brilliant Retina display, fast processors, and a sleek design thats perfect for creative professionals.',
      keywords: ['laptop', 'Apple', 'MacBook', 'professional'],
      isFeatured: true
    },
    {
      id: 11,
      name: 'Levis 501 Original Fit Jeans',
      image: '',
      price: 79,
      shopName: 'FashionDen',
      distance: 1.5,
      description: 'Get the classic style and comfort of Levis 501 Original Fit Jeans. These timeless jeans feature a straight leg and a durable denim construction.',
      keywords: ['jeans', 'denim', 'fashion', 'clothing'],
      isFeatured: false
    },
    {
      id: 12,
      name: 'Fujifilm Instax Mini 9 Instant Camera',
      image: '',
      price: 69,
      shopName: 'SnapShot',
      distance: 3.2,
      description: 'Capture and print your favorite moments instantly with the Fujifilm Instax Mini 9 Instant Camera. It offers simple operation and produces credit card-sized prints.',
      keywords: ['camera', 'instant', 'photography', 'Fujifilm'],
      isFeatured: false
    },
    {
      id: 13,
      name: 'Nike Air Max 90 Sneakers',
      image: '',
      price: 119,
      shopName: 'SportWorld',
      distance: 2.8,
      description: 'Step up your sneaker game with the iconic Nike Air Max 90. These stylish sneakers feature a comfortable fit, cushioned midsole, and a classic design.',
      keywords: ['sneakers', 'shoes', 'Nike', 'sport'],
      isFeatured: false
    },
    {
      id: 14,
      name: 'KitchenAid Artisan Stand Mixer',
      image: '',
      price: 349,
      shopName: 'CulinaryEssentials',
      distance: 4.5,
      description: 'Unleash your inner chef with the KitchenAid Artisan Stand Mixer. It offers versatile mixing options, a powerful motor, and a range of attachments for all your culinary creations.',
      keywords: ['kitchen', 'mixer', 'baking', 'cooking'],
      isFeatured: false
    },
    {
      id: 15,
      name: 'Ray-Ban Classic Wayfarer Sunglasses',
      image: '',
      price: 149,
      shopName: 'SunShades',
      distance: 2.3,
      description: 'Add a touch of timeless style to your look with Ray-Ban Classic Wayfarer Sunglasses. These iconic shades offer UV protection and a fashionable design.',
      keywords: ['sunglasses', 'eyewear', 'fashion', 'accessories'],
      isFeatured: false
    },
    {
      id: 16,
      name: 'Fitbit Charge 4 Fitness Tracker',
      image: '',
      price: 129,
      shopName: 'ActiveLifestyle',
      distance: 3.9,
      description: 'Track your fitness goals and stay motivated with the Fitbit Charge 4 Fitness Tracker. It monitors your heart rate, tracks your workouts, and offers insights into your sleep patterns.',
      keywords: ['fitness', 'tracker', 'health', 'activity'],
      isFeatured: false
    },
    {
      id: 17,
      name: 'Samsonite Omni Hardside Luggage',
      image: '',
      price: 159,
      shopName: 'TravelEssentials',
      distance: 5.1,
      description: 'Travel in style with the Samsonite Omni Hardside Luggage. It features a durable and lightweight design, spinner wheels, and ample packing space for all your travel needs.',
      keywords: ['luggage', 'travel', 'suitcase', 'bag'],
      isFeatured: false
    },
    {
      id: 18,
      name: 'YETI Rambler 20 oz Tumbler',
      image: '',
      price: 29,
      shopName: 'OutdoorGear',
      distance: 4.2,
      description: 'Keep your drinks hot or cold for longer with the YETI Rambler 20 oz Tumbler. It features durable construction, a leak-resistant lid, and a sweat-free design.',
      keywords: ['tumbler', 'drinkware', 'outdoor', 'insulated'],
      isFeatured: false
    },
    {
      id: 19,
      name: 'Patagonia Better Sweater Fleece Jacket',
      image: '',
      price: 129,
      shopName: 'OutdoorAdventure',
      distance: 3.7,
      description: 'Stay warm and stylish in the Patagonia Better Sweater Fleece Jacket. It offers a cozy feel, a full-zip design, and a versatile look for outdoor adventures.',
      keywords: ['jacket', 'fleece', 'outdoor', 'clothing'],
      isFeatured: false
    },
    {
      id: 20,
      name: 'BOSE SoundLink Revolve Bluetooth Speaker',
      image: 'https://example.com/bosemusic.jpg',
      price: 199,
      shopName: 'AudioMasters',
      distance: 2.6,
      description: 'Enjoy immersive sound and portability with the BOSE SoundLink Revolve Bluetooth Speaker. It delivers deep, 360-degree sound and features a sleek design.',
      keywords: ['speaker', 'Bluetooth', 'audio', 'music'],
      isFeatured: false
    }
  ];