export type productData = {
  id: Number,
  name: string,
  image: string,
  price: number,
  shopName: string,
  distance: number,
  description: string,
  keywords: string[];
  isFeatured: boolean,
}

export const products: productData[] = [
    {
      id: 0,
      name: 'AP Royale Oak Gold',
      image: '/RoyaleOak.png',
      price: 1239,
      shopName: 'Watches & jewerlery',
      distance: 0.4,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: true,
    },
    {
      id: 1,
      name: 'AP Royale Oak',
      image: '/RoyaleOak.png',
      price: 2343,
      shopName: 'Watches & jewerlery',
      distance: 0.4,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: true,
    },
    {
      id: 2,
      name: 'AP Royale Oak',
      image: '/RoyaleOak.png',
      price: 999,
      shopName: 'Watches & jewerlery',
      distance: 0.9,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: false,
    },
    {
      id: 3,
      name: 'AP Royale Oak',
      image: '/RoyaleOak.png',
      price: 109,
      shopName: 'Watches & jewerlery',
      distance: 5,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: false,
    },
    {
      id: 4,
      name: 'AP Royale Oak',
      image: '/RoyaleOak.png',
      price: 1239,
      shopName: 'Watches & jewerlery',
      distance: 0.23,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: false,
    },
    {
      id: 5,
      name: 'AP Royale Oak',
      image: '/RoyaleOak.png',
      price: 2343,
      shopName: 'Watches & jewerlery',
      distance: 0.4,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: false,
    },
    {
      id: 6,
      name: 'AP Royale Oak',
      image: '/RoyaleOak.png',
      price: 999,
      shopName: 'Watches & jewerlery',
      distance: 0.9,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: false,
    },
    {
      id: 7,
      name: 'AP Royale Oak',
      image: '/RoyaleOak.png',
      price: 109,
      shopName: 'Watches & jewerlery',
      distance: 5,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: false,
    },
    {
      id: 8,
      name: 'AP Royale Oak',
      image: '/RoyaleOak.png',
      price: 109,
      shopName: 'Watches & jewerlery',
      distance: 5,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: false,
    },
    {
      id: 9,
      name: 'AP Royale Oak',
      image: '/RoyaleOak.png',
      price: 109,
      shopName: 'Watches & jewerlery',
      distance: 5,
      description: 'This is the description for Product 1',
      keywords: ['keyword1', 'keyword2', 'keyword3'],
      isFeatured: false,
    },
  ];